import React, { useState, useEffect, useMemo, useCallback, useRef } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { 
  ArrowLeft, Plus, Trash2, Loader2, Database, Printer, RefreshCw, Eye, EyeOff, Upload, Palette, FileText
} from 'lucide-react';
import toast from 'react-hot-toast';
import { PDFDownloadLink, PDFViewer } from '@react-pdf/renderer';
import FiscalInvoice from '../../components/invoices/FiscalInvoice';
import { TEMPLATES } from '../../components/invoices/templates/index.js';
import type { TemplateId } from '../../components/invoices/templates/index.js';
import api from '../../lib/axios';

const InvoiceGenerator: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const [clients, setClients] = useState<any[]>([]);
  const [deals, setDeals] = useState<any[]>([]);
  const [catalog, setCatalog] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [autoGeneratedNumber, setAutoGeneratedNumber] = useState('');
  const [isCustomNumber, setIsCustomNumber] = useState(false);

  const [formData, setFormData] = useState({
    invoiceNumber: '',
    invoiceDate: new Date().toISOString().split('T')[0],
    reverseCharge: "N",
    gstConfig: 'INTRA',
    upiId: "",
    transportMode: "",
    vehicleNumber: "",
    dateOfSupply: new Date().toISOString().split('T')[0],
    placeOfSupply: "LOCAL",
    descriptionHeader: "Service/Product Delivery Details",
    templateId: 'gst-standard' as TemplateId,
    currency: '₹',
    projectName: '',
    servicePeriod: '',
    billingType: 'Fixed',
    projectScope: '',
    seller: {
      name: "Your Company",
      address: "",
      phone: [""],
      email: "",
      gstin: "",
      msmeRegNo: "",
      logoUrl: "",
      accentColor: "#6366F1",
      state: "LOCAL",
      stateCode: "01",
      bank: { name: "", branch: "", accountNo: "", ifsc: "" },
      upiId: ""
    },
    buyer: {
      name: "",
      address: "",
      gstin: "",
      state: "",
      stateCode: ""
    },
    items: [
      { id: Date.now(), description: "", hsn: "", qty: 1, rate: 0, discount: 0, cgstRate: 9, sgstRate: 9, igstRate: 0 }
    ],
    terms: "1. Payment should be made within 15 days.\n2. Interest may be charged on delayed payments.",
    showDigitalSignature: false,
    signatureUrl: "",
    showUpiQr: true
  });

  const getNextAutoNumber = useCallback((existingInvoices: any[]) => {
    const today = new Date();
    const year = today.getFullYear();
    const prefix = `INV-${year}-`;
    
    const relevantInvoices = existingInvoices.filter(inv => inv.invoiceNumber && inv.invoiceNumber.startsWith(prefix));
    let maxSeq = 0;
    
    if (relevantInvoices.length > 0) {
        const sequences = relevantInvoices.map(inv => {
            const parts = inv.invoiceNumber.split('-');
            return parseInt(parts[parts.length - 1]) || 0;
        });
        maxSeq = Math.max(...sequences);
    }

    return `${prefix}${String(maxSeq + 1).padStart(4, '0')}`;
  }, []);

  const fetchInitialData = async () => {
    try {
      setIsLoading(true);
      const [meRes, clientsRes, dealsRes, assetsRes, invoicesRes] = await Promise.all([
        api.get('/auth/me'),
        api.get('/clients'),
        api.get('/deals'),
        api.get('/assets'),
        api.get('/invoices')
      ]);
      
      const org = meRes.data.organization;
      const dynamicSeller = {
        name: org.name,
        address: org.address || "Address not set",
        phone: [org.phone || ""],
        email: org.email || "",
        gstin: org.gstin || "",
        msmeRegNo: org.msmeRegNo || "",
        logoUrl: org.logoUrl || "",
        accentColor: org.accentColor || "#6366F1",
        state: "LOCAL",
        stateCode: "01",
        bank: {
          name: org.bankName || "",
          branch: org.bankBranch || "",
          accountNo: org.accountNumber || "",
          ifsc: org.ifscCode || ""
        },
        upiId: org.upiId || ""
      };

      setClients(clientsRes.data);
      setDeals(dealsRes.data);
      
      const assetCatalog = assetsRes.data.map((a: any) => ({
        id: a.id,
        description: a.name,
        hsn_code: "9900",
        default_rate: 0,
        cgst_rate: 9,
        sgst_rate: 9
      }));
      setCatalog(assetCatalog);

      if (id) {
        try {
          const invRes = await api.get(`/invoices/${id}`);
          const inv = invRes.data;
          
          setFormData({
            invoiceNumber: inv.invoiceNumber,
            invoiceDate: new Date(inv.invoiceDate).toISOString().split('T')[0],
            reverseCharge: inv.reverseCharge || 'N',
            gstConfig: inv.igstAmount > 0 ? 'INTER' : (inv.cgstAmount > 0 ? 'INTRA' : 'NONE'),
            upiId: inv.upiId || org.upiId || '',
            transportMode: inv.transportMode || '',
            vehicleNumber: inv.vehicleNumber || '',
            dateOfSupply: inv.dateOfSupply ? new Date(inv.dateOfSupply).toISOString().split('T')[0] : new Date(inv.invoiceDate).toISOString().split('T')[0],
            placeOfSupply: inv.placeOfSupply || 'LOCAL',
            descriptionHeader: inv.notes || 'Service Delivery',
            templateId: inv.templateId || 'gst-standard',
            currency: inv.templateData?.currency || inv.currency || '₹',
            projectName: inv.templateData?.projectName || '',
            servicePeriod: inv.templateData?.servicePeriod || '',
            billingType: inv.templateData?.billingType || 'Fixed',
            projectScope: inv.templateData?.projectScope || '',
            seller: {
              name: inv.organization?.name || dynamicSeller.name,
              address: inv.organization?.address || dynamicSeller.address,
              phone: inv.organization?.phone ? [inv.organization.phone] : dynamicSeller.phone,
              email: inv.organization?.email || dynamicSeller.email,
              gstin: inv.organization?.gstin || dynamicSeller.gstin,
              msmeRegNo: inv.organization?.msmeRegNo || dynamicSeller.msmeRegNo,
              logoUrl: inv.organization?.logoUrl || dynamicSeller.logoUrl,
              accentColor: inv.organization?.accentColor || dynamicSeller.accentColor,
              state: 'LOCAL',
              stateCode: '01',
              bank: inv.bankDetails ? (typeof inv.bankDetails === 'string' ? JSON.parse(inv.bankDetails) : inv.bankDetails) : dynamicSeller.bank,
              upiId: inv.upiId || dynamicSeller.upiId
            },
            buyer: {
              name: inv.client?.name || '',
              address: inv.client?.address || '',
              gstin: inv.client?.gstin || '',
              state: inv.client?.state || '',
              stateCode: '01'
            },
            items: inv.invoiceItems && inv.invoiceItems.length > 0 ? inv.invoiceItems.map((item: any, idx: number) => ({
              id: item.id || Date.now() + idx,
              description: item.description || '',
              hsn: item.hsn || '',
              qty: item.quantity || 1,
              rate: item.rate || 0,
              discount: item.discount || 0,
              cgstRate: item.cgstRate || 0,
              sgstRate: item.sgstRate || 0,
              igstRate: item.igstRate || 0
            })) : [
              { id: Date.now(), description: "", hsn: "", qty: 1, rate: 0, discount: 0, cgstRate: 9, sgstRate: 9, igstRate: 0 }
            ],
            terms: inv.paymentTerms || "1. Payment should be made within 15 days.",
            showDigitalSignature: inv.showDigitalSignature ?? false,
            signatureUrl: inv.signatureUrl || '',
            showUpiQr: inv.showUpiQr ?? true
          });
        } catch (err) {
          toast.error('Failed to load existing invoice data');
        }
      } else {
        const nextAuto = getNextAutoNumber(invoicesRes.data || []);
        setAutoGeneratedNumber(nextAuto);
        
        setFormData(prev => ({ 
          ...prev, 
          invoiceNumber: nextAuto,
          seller: dynamicSeller,
          upiId: org.upiId || prev.upiId
        }));
      }
    } catch (error) {
      toast.error('Failed to load CRM data');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchInitialData();
  }, [id]);

  const totals = useMemo(() => {
    let newTaxableTotal = 0;
    let newCgstTotal = 0;
    let newSgstTotal = 0;
    let newIgstTotal = 0;

    const itemsWithCalc = formData.items.map((item, index) => {
      const amount = item.qty * item.rate;
      const taxable = amount - item.discount;
      
      let cgst = 0;
      let sgst = 0;
      let igst = 0;

      if (formData.gstConfig === 'INTRA') {
        cgst = taxable * (item.cgstRate / 100);
        sgst = taxable * (item.sgstRate / 100);
      } else if (formData.gstConfig === 'INTER') {
        igst = taxable * (18 / 100); 
      }
      
      newTaxableTotal += taxable;
      newCgstTotal += cgst;
      newSgstTotal += sgst;
      newIgstTotal += igst;

      return { 
        ...item, 
        sNo: index + 1,
        amount, 
        taxableValue: taxable, 
        cgstAmount: cgst, 
        sgstAmount: sgst, 
        igstAmount: igst, 
        total: taxable + cgst + sgst + igst 
      };
    });

    return {
      items: itemsWithCalc,
      taxableTotal: newTaxableTotal,
      cgstTotal: newCgstTotal,
      sgstTotal: newSgstTotal,
      igstTotal: newIgstTotal,
      grandTotal: newTaxableTotal + newCgstTotal + newSgstTotal + newIgstTotal
    };
  }, [formData]);

  const pdfData = useMemo(() => ({
    ...formData,
    items: totals.items,
    subtotal: totals.taxableTotal,
    cgstTotal: totals.cgstTotal,
    sgstTotal: totals.sgstTotal,
    igstTotal: totals.igstTotal,
    grandTotal: totals.grandTotal,
    templateId: formData.templateId
  }), [formData, totals]);

  const handleClientSelect = (clientId: string) => {
    const client = clients.find(c => c.id === clientId);
    if (client) {
      setFormData({
        ...formData,
        buyer: {
          name: client.name,
          address: client.address,
          gstin: client.gstin,
          state: client.state,
          stateCode: '01'
        }
      });
    }
  };

  const handleDealSelect = (dealId: string) => {
    const deal = deals.find(d => d.id === dealId);
    if (deal) {
      const dealItems = deal.activityLogs?.map((log: any) => ({
        id: Date.now() + Math.random(),
        description: log.asset?.name || "Service Item",
        hsn: "9900",
        qty: 1,
        rate: 0,
        discount: 0,
        cgstRate: 9,
        sgstRate: 9,
        igstRate: 0
      })) || [];

      setFormData({
        ...formData,
        descriptionHeader: `Project Engagement: ${deal.title}`,
        items: dealItems.length > 0 ? dealItems : formData.items
      });
    }
  };

  const addItem = () => {
    setFormData({
      ...formData,
      items: [...formData.items, { id: Date.now(), description: "", hsn: "", qty: 1, rate: 0, discount: 0, cgstRate: 9, sgstRate: 9, igstRate: 0 }]
    });
  };

  const removeItem = (id: number) => {
    if (formData.items.length === 1) return;
    setFormData({
      ...formData,
      items: formData.items.filter(item => item.id !== id)
    });
  };

  const saveInvoice = async () => {
    try {
      setIsLoading(true);
      const payload = {
        invoiceNumber: formData.invoiceNumber,
        clientId: clients.find(c => c.name === formData.buyer.name)?.id || '',
        dealId: deals.find(d => formData.descriptionHeader.includes(d.title))?.id || null,
        invoiceDate: formData.invoiceDate ? new Date(formData.invoiceDate) : new Date(),
        lineItems: JSON.stringify(totals.items),
        subtotal: totals.taxableTotal,
        taxableAmount: totals.taxableTotal,
        cgstAmount: totals.cgstTotal,
        sgstAmount: totals.sgstTotal,
        igstAmount: totals.igstTotal,
        totalAmount: totals.grandTotal,
        notes: formData.descriptionHeader,
        reverseCharge: formData.reverseCharge,
        upiId: formData.upiId,
        showUpiQr: formData.showUpiQr,
        showDigitalSignature: formData.showDigitalSignature,
        signatureUrl: formData.signatureUrl,
        templateId: formData.templateId,
        currency: formData.currency,
        projectName: formData.projectName,
        servicePeriod: formData.servicePeriod,
        billingType: formData.billingType,
        projectScope: formData.projectScope
      };

      if (id) {
        await api.put(`/invoices/${id}`, payload);
      } else {
        await api.post('/invoices', payload);
      }

      toast.success('Invoice saved successfully');
      navigate('/invoices');
    } catch (error) {
      toast.error('Failed to save invoice');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-screen bg-bg-primary overflow-hidden print:bg-white text-text-primary">
      <div className="h-14 bg-bg-surface border-b border-border flex items-center justify-between px-6 shrink-0 print:hidden">
        <div className="flex items-center gap-4">
          <button onClick={() => navigate('/invoices')} className="p-2 hover:bg-bg-surface-2 rounded-lg transition-colors">
            <ArrowLeft size={20} />
          </button>
          <h1 className="text-sm font-black uppercase tracking-widest">{id ? 'Edit Invoice' : 'New Invoice'}</h1>
        </div>
        
        <div className="flex items-center gap-3">
          <button 
            onClick={saveInvoice}
            disabled={isLoading}
            className="bg-bg-surface-2 border border-border text-text-primary px-4 py-2 rounded-lg font-black text-xs uppercase tracking-widest hover:border-accent-orange transition-all flex items-center gap-2"
          >
            {isLoading ? <Loader2 size={16} className="animate-spin" /> : <Database size={16} />}
            Record & Save
          </button>
          
          <PDFDownloadLink document={<FiscalInvoice invoiceData={pdfData} />} fileName={`${formData.invoiceNumber || 'invoice'}.pdf`}>
            {({ loading }) => (
              <button disabled={loading} className="bg-accent-orange text-white px-6 py-2 rounded-lg font-black text-xs uppercase tracking-widest flex items-center gap-2 shadow-lg shadow-accent-orange/20 hover:bg-accent-orange/90 transition-all disabled:opacity-50">
                {loading ? <Loader2 size={16} className="animate-spin" /> : <Printer size={16} />}
                {loading ? 'Compiling...' : 'Download PDF'}
              </button>
            )}
          </PDFDownloadLink>
        </div>
      </div>

      <div className="flex flex-col lg:flex-row flex-1 overflow-hidden print:block">
        <div className="w-full lg:w-1/2 overflow-y-auto p-8 border-r border-border bg-bg-primary custom-scrollbar print:hidden">
          <div className="space-y-8 max-w-2xl mx-auto pb-20">
            <div className="card space-y-6">
              <h2 className="text-[15px] font-black text-accent-orange uppercase tracking-[2px] border-b border-border pb-3">01. Invoice Meta</h2>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="text-[14px] font-black text-text-muted uppercase">Invoice Number</label>
                  <div className="flex gap-2">
                    <button
                      onClick={() => {
                        const next = isCustomNumber ? autoGeneratedNumber : formData.invoiceNumber;
                        setIsCustomNumber(false);
                        setFormData({...formData, invoiceNumber: autoGeneratedNumber});
                      }}
                      className={`px-3 py-2 rounded-lg text-[13px] font-black uppercase tracking-widest transition-all ${!isCustomNumber ? 'bg-accent-orange text-white' : 'bg-bg-surface-2 text-text-muted border border-border'}`}
                    >Auto</button>
                    <button
                      onClick={() => setIsCustomNumber(true)}
                      className={`px-3 py-2 rounded-lg text-[13px] font-black uppercase tracking-widest transition-all ${isCustomNumber ? 'bg-accent-orange text-white' : 'bg-bg-surface-2 text-text-muted border border-border'}`}
                    >Manual</button>
                  </div>
                  {isCustomNumber ? (
                    <input type="text" className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[16px] outline-none" value={formData.invoiceNumber} onChange={e => setFormData({...formData, invoiceNumber: e.target.value})} />
                  ) : (
                    <div className="flex gap-2 items-center">
                      <input type="text" className="w-full bg-bg-surface border border-border rounded-xl px-3 py-2 text-[16px] outline-none font-bold text-accent-blue" value={formData.invoiceNumber} readOnly />
                      <button
                        onClick={async () => {
                          try {
                            const res = await api.get('/invoices');
                            const next = getNextAutoNumber(res.data || []);
                            setAutoGeneratedNumber(next);
                            setFormData({...formData, invoiceNumber: next});
                            toast.success('New number generated');
                          } catch { toast.error('Failed to generate');
                          }
                        }}
                        className="p-2 bg-bg-surface-2 border border-border rounded-lg text-text-muted hover:text-accent-orange transition-colors"
                        title="Generate new number"
                      ><RefreshCw size={16} /></button>
                    </div>
                  )}
                </div>
                <div className="space-y-1.5">
                  <label className="text-[14px] font-black text-text-muted uppercase">Invoice Date</label>
                  <input type="date" className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[15px] outline-none" value={formData.invoiceDate} onChange={e => setFormData({...formData, invoiceDate: e.target.value})} />
                </div>
              </div>
            </div>

            <div className="card space-y-6">
              <h2 className="text-[15px] font-black text-accent-purple uppercase tracking-[2px] border-b border-border pb-3">02. Template & Branding</h2>
              
              <div className="space-y-4">
                <label className="text-[14px] font-black text-text-muted uppercase">Invoice Template</label>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                  {(Object.entries(TEMPLATES) as [TemplateId, typeof TEMPLATES[TemplateId]][]).map(([id, tmpl]) => (
                    <button
                      key={id}
                      onClick={() => setFormData({...formData, templateId: id})}
                      className={`p-3 rounded-xl border-2 text-left transition-all ${
                        formData.templateId === id
                          ? 'border-accent-purple bg-accent-purple/5 shadow-lg shadow-accent-purple/10'
                          : 'border-border bg-bg-surface-2 hover:border-accent-purple/40'
                      }`}
                    >
                      <div className="flex items-center gap-2 mb-1.5">
                        <FileText size={14} className={formData.templateId === id ? 'text-accent-purple' : 'text-text-muted'} />
                        <span className={`text-[12px] font-black uppercase tracking-wider ${formData.templateId === id ? 'text-accent-purple' : 'text-text-primary'}`}>
                          {tmpl.name}
                        </span>
                      </div>
                      <p className="text-[11px] text-text-muted leading-tight">{tmpl.description}</p>
                    </button>
                  ))}
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4 pt-2 border-t border-border">
                <div className="space-y-1.5">
                  <label className="text-[14px] font-black text-text-muted uppercase">Company Logo</label>
                  <div className="flex items-center gap-3">
                    <div className="w-16 h-16 rounded-xl border-2 border-border bg-bg-surface-2 flex items-center justify-center overflow-hidden">
                      {formData.seller.logoUrl ? (
                        <img src={formData.seller.logoUrl} alt="Logo" className="w-full h-full object-contain" />
                      ) : (
                        <Upload size={20} className="text-text-muted" />
                      )}
                    </div>
                    <button
                      onClick={() => {
                        const url = prompt('Enter logo image URL:');
                        if (url) setFormData({...formData, seller: {...formData.seller, logoUrl: url}});
                      }}
                      className="px-3 py-2 bg-bg-surface-2 border border-border rounded-lg text-[12px] font-bold uppercase tracking-wider text-text-muted hover:text-accent-blue transition-all"
                    >Set Logo URL</button>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <label className="text-[14px] font-black text-text-muted uppercase">Accent Color</label>
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl border-2 border-border" style={{ backgroundColor: formData.seller.accentColor || '#6366F1' }} />
                    <input
                      type="color"
                      value={formData.seller.accentColor || '#6366F1'}
                      onChange={e => setFormData({...formData, seller: {...formData.seller, accentColor: e.target.value}})}
                      className="w-20 h-10 rounded-xl border border-border cursor-pointer bg-transparent"
                    />
                    <span className="text-[11px] text-text-muted font-mono">{formData.seller.accentColor}</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="card space-y-6">
              <h2 className="text-[15px] font-black text-accent-blue uppercase tracking-[2px] border-b border-border pb-3">03. Recipient Information</h2>
              <div className="space-y-4">
                <div className="space-y-1.5">
                  <label className="text-[14px] font-black text-text-muted uppercase">Select Client</label>
                  <select className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[16px] outline-none" onChange={(e) => handleClientSelect(e.target.value)}>
                    <option value="">Manual Entry...</option>
                    {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                  </select>
                </div>
                <div className="space-y-1.5">
                  <label className="text-[14px] font-black text-text-muted uppercase">Select Related Deal</label>
                  <select className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[16px] outline-none" onChange={(e) => handleDealSelect(e.target.value)}>
                    <option value="">No Deal Linked...</option>
                    {deals.map(d => <option key={d.id} value={d.id}>{d.title}</option>)}
                  </select>
                </div>
                <div className="space-y-1.5">
                  <label className="text-[14px] font-black text-text-muted uppercase">Buyer Name</label>
                  <input type="text" className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[16px] outline-none font-bold" value={formData.buyer.name} onChange={e => setFormData({...formData, buyer: {...formData.buyer, name: e.target.value}})} />
                </div>
                <div className="space-y-1.5">
                  <label className="text-[14px] font-black text-text-muted uppercase">Billing Address</label>
                  <textarea rows={2} className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[15px] outline-none" value={formData.buyer.address} onChange={e => setFormData({...formData, buyer: {...formData.buyer, address: e.target.value}})} />
                </div>
              </div>
            </div>

            <div className="card space-y-6">
              <div className="flex justify-between items-center border-b border-border pb-3">
                <h2 className="text-[14px] font-black text-success uppercase tracking-[2px]">04. Line Items</h2>
                <button onClick={addItem} className="text-xs font-bold text-accent-orange flex items-center gap-1 hover:underline">
                  <Plus size={14} /> Add Item
                </button>
              </div>
              <div className="space-y-4">
                {formData.items.map((item, index) => (
                  <div key={item.id} className="p-4 bg-bg-surface-2 rounded-xl border border-border relative group">
                    <button onClick={() => removeItem(item.id)} className="absolute -top-2 -right-2 w-6 h-6 bg-danger text-white rounded-full flex items-center justify-center shadow-lg opacity-0 group-hover:opacity-100 transition-opacity">
                      <Trash2 size={12} />
                    </button>
                    <div className="grid grid-cols-6 gap-4">
                      <div className="col-span-4 space-y-1.5">
                        <label className="text-[12px] font-black text-text-muted uppercase">Description</label>
                        <input type="text" className="w-full bg-bg-surface border border-border rounded-lg px-2 py-1.5 text-[15px] outline-none" value={item.description} onChange={e => {
                          const newItems = [...formData.items];
                          newItems[index].description = e.target.value;
                          setFormData({...formData, items: newItems});
                        }} />
                      </div>
                      <div className="col-span-1 space-y-1.5">
                        <label className="text-[12px] font-black text-text-muted uppercase">Qty</label>
                        <input type="number" className="w-full bg-bg-surface border border-border rounded-lg px-2 py-1.5 text-[15px] outline-none" value={item.qty} onChange={e => {
                          const newItems = [...formData.items];
                          newItems[index].qty = parseFloat(e.target.value) || 0;
                          setFormData({...formData, items: newItems});
                        }} />
                      </div>
                      <div className="col-span-1 space-y-1.5">
                        <label className="text-[12px] font-black text-text-muted uppercase">Rate</label>
                        <input type="number" className="w-full bg-bg-surface border border-border rounded-lg px-2 py-1.5 text-[15px] outline-none font-bold" value={item.rate} onChange={e => {
                          const newItems = [...formData.items];
                          newItems[index].rate = parseFloat(e.target.value) || 0;
                          setFormData({...formData, items: newItems});
                        }} />
              </div>
            </div>

            <div className="card space-y-6">
              <h2 className="text-[15px] font-black text-accent-purple uppercase tracking-[2px] border-b border-border pb-3">02-B. Invoice Settings</h2>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="text-[14px] font-black text-text-muted uppercase">Currency</label>
                  <select
                    value={formData.currency}
                    onChange={e => setFormData({...formData, currency: e.target.value})}
                    className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[16px] outline-none font-bold"
                  >
                    <option value="₹">INR (₹) - Indian Rupee</option>
                    <option value="$">USD ($) - US Dollar</option>
                    <option value="€">EUR (€) - Euro</option>
                    <option value="£">GBP (£) - British Pound</option>
                    <option value="¥">JPY (¥) - Japanese Yen</option>
                    <option value="A$">AUD (A$) - Australian Dollar</option>
                    <option value="C$">CAD (C$) - Canadian Dollar</option>
                    <option value="S$">SGD (S$) - Singapore Dollar</option>
                    <option value="AED">AED - UAE Dirham</option>
                  </select>
                </div>
              </div>

              {formData.templateId === 'digital-services' && (
                <div className="grid grid-cols-2 gap-4 pt-2 border-t border-border">
                  <div className="space-y-1.5">
                    <label className="text-[14px] font-black text-text-muted uppercase">Project / Service Name</label>
                    <input type="text" className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[16px] outline-none" value={formData.projectName} onChange={e => setFormData({...formData, projectName: e.target.value})} placeholder="Website Redesign" />
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-[14px] font-black text-text-muted uppercase">Service Period</label>
                    <input type="text" className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[16px] outline-none" value={formData.servicePeriod} onChange={e => setFormData({...formData, servicePeriod: e.target.value})} placeholder="Jan 2026 - Mar 2026" />
                  </div>
                </div>
              )}

              {formData.templateId === 'freelancer' && (
                <div className="grid grid-cols-2 gap-4 pt-2 border-t border-border">
                  <div className="space-y-1.5">
                    <label className="text-[14px] font-black text-text-muted uppercase">Billing Type</label>
                    <select
                      value={formData.billingType}
                      onChange={e => setFormData({...formData, billingType: e.target.value})}
                      className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[16px] outline-none font-bold"
                    >
                      <option value="Hourly">Hourly</option>
                      <option value="Fixed">Fixed Price</option>
                      <option value="Retainer">Retainer</option>
                      <option value="Milestone">Milestone Based</option>
                    </select>
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-[14px] font-black text-text-muted uppercase">Project Scope</label>
                    <input type="text" className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[16px] outline-none" value={formData.projectScope} onChange={e => setFormData({...formData, projectScope: e.target.value})} placeholder="Consulting & Strategy" />
                  </div>
                </div>
              )}
            </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="card space-y-6">
              <h2 className="text-[15px] font-black text-accent-orange uppercase tracking-[2px] border-b border-border pb-3">05. Payment & UPI QR</h2>
              <div className="space-y-4">
                <div className="space-y-1.5">
                  <label className="text-[14px] font-black text-text-muted uppercase">UPI ID (for QR)</label>
                  <input type="text" className="w-full bg-bg-surface-2 border border-border rounded-xl px-3 py-2 text-[16px] outline-none" value={formData.upiId} onChange={e => setFormData({...formData, upiId: e.target.value})} placeholder="merchant@upi" />
                </div>
                {formData.upiId && (
                  <div className="flex items-center gap-6 p-4 bg-bg-surface-2 rounded-xl border border-border">
                    <div className="bg-white p-2 rounded-lg shadow-md">
                      <img src={`https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(`upi://pay?pa=${formData.upiId}&pn=${encodeURIComponent(formData.seller.name)}&am=${totals.grandTotal.toFixed(2)}&cu=INR`)}`} alt="UPI QR" className="w-28 h-28" />
                    </div>
                    <div className="space-y-2 text-[14px]">
                      <p className="font-bold text-text-primary">Scan to Pay</p>
                      <p className="text-text-muted">UPI: {formData.upiId}</p>
                      <p className="text-text-muted">Amount: ₹{totals.grandTotal.toFixed(2)}</p>
                      <button
                        onClick={() => setFormData({...formData, showUpiQr: !formData.showUpiQr})}
                        className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-[13px] font-black uppercase tracking-widest transition-all ${formData.showUpiQr ? 'bg-success/10 text-success' : 'bg-bg-surface text-text-muted'}`}
                      >
                        {formData.showUpiQr ? <Eye size={14} /> : <EyeOff size={14} />}
                        {formData.showUpiQr ? 'Show on Invoice' : 'Hidden on Invoice'}
                      </button>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
 
        <div className="flex-1 bg-bg-surface-2 overflow-hidden p-4 print:p-0 print:bg-white flex flex-col">
          <PDFViewer width="100%" height="100%" showToolbar={false}>
            <FiscalInvoice invoiceData={pdfData} />
          </PDFViewer>
        </div>
      </div>
    </div>
  );
};

export default InvoiceGenerator;
